image: gitpod/workspace-full

tasks:
  - name: Start Harvest Q Orchestrate API
    init: |
      cd server
      npm install
    command: |
      cd server
      npm run dev

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-vscode.js-debug
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
