image: gitpod/workspace-full
tasks:
  - init: npm i -g http-server
    command: http-server -c-1 . -p 8080
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - ms-vscode.js-debug
