image: gitpod/workspace-full

tasks:
  - name: Start Harvest Q Server
    init: |
      npm install
    command: |
      npm run start

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-vscode.js-debug
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint 
